version: 0.2.0
image: Visual Studio 2017
configuration: Release
skip_non_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore src\Autofac.AttributeExtensions.sln
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: SlxJp/Oj+p1sAv9IZjrA4sIkaPkxu6r7QAWnZyynWsBPqE5GA9UXax3JlXU6sTLR
